// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: stacpchina

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabPage1;
lv_obj_t * ui_Chart2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label10;
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_TabPage3;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
lv_obj_t * ui_TabPage4;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label20;
lv_obj_t * ui_TextArea2;
lv_obj_t * ui_TabPage5;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Chart3;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label24;
lv_obj_t * ui_TabPage6;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
// const lv_img_dsc_t * ui_imgset_frame_[1] = {&ui_img_frame_3_png};
// const lv_img_dsc_t * ui_imgset_frame_[1] = {&ui_img_frame_1_png};
// const lv_img_dsc_t * ui_imgset_lorawan_gateway_on_coremp[1] = {&ui_img_lorawan_gateway_on_coremp135_png};
// const lv_img_dsc_t * ui_imgset_lora_[1] = {&ui_img_lora_1_png};
// const lv_img_dsc_t * ui_imgset_rectangle_[2] = {&ui_img_rectangle_15_png, &ui_img_rectangle_16_png};
// const lv_img_dsc_t * ui_imgset_vector_[3] = {&ui_img_vector_1_png, &ui_img_vector_2_png, &ui_img_vector_3_png};
// const lv_img_dsc_t * ui_imgset_battery[1] = {&ui_img_battery2_png};
// const lv_img_dsc_t * ui_imgset_cm4_stack_logo[1] = {&ui_img_cm4_stack_logo1_png};
// const lv_img_dsc_t * ui_imgset_1402240725[1] = {&ui_img_1858829983};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
