// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: stacpchina

#ifndef _STACPCHINA_UI_H
#define _STACPCHINA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_TabPage4;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_TabPage5;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_TabPage6;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_normal_jpg_png);    // assets/normal.jpg.png
LV_IMG_DECLARE(ui_img_shake_head_jpg_png);    // assets/shake_head.jpg.png
LV_IMG_DECLARE(ui_img_turn_left_jpg_png);    // assets/turn_left.jpg.png
LV_IMG_DECLARE(ui_img_turn_right_jpg_png);    // assets/turn_right.jpg.png
LV_IMG_DECLARE(ui_img_nod_head_jpg_png);    // assets/nod_head.jpg.png
// LV_IMG_DECLARE(ui_img_frame_3_png);    // assets/Frame 3.png
// LV_IMG_DECLARE(ui_img_frame_1_png);    // assets/Frame_1.png
// LV_IMG_DECLARE(ui_img_lorawan_gateway_on_coremp135_png);    // assets/LoRaWAN Gateway on CoreMP135.png
// LV_IMG_DECLARE(ui_img_lora_1_png);    // assets/Lora 1.png
// LV_IMG_DECLARE(ui_img_rectangle_15_png);    // assets/Rectangle 15.png
// LV_IMG_DECLARE(ui_img_rectangle_16_png);    // assets/Rectangle 16.png
// LV_IMG_DECLARE(ui_img_vector_1_png);    // assets/Vector 1.png
// LV_IMG_DECLARE(ui_img_vector_2_png);    // assets/Vector 2.png
// LV_IMG_DECLARE(ui_img_vector_3_png);    // assets/Vector 3.png
// LV_IMG_DECLARE(ui_img_battery2_png);    // assets/battery2.png
// LV_IMG_DECLARE(ui_img_cm4_stack_logo1_png);    // assets/cm4_stack_logo1.png
// LV_IMG_DECLARE(ui_img_1858829983);    // assets/package-1.png

// // FONTS
// LV_FONT_DECLARE(ui_font_mono13);
// LV_FONT_DECLARE(ui_font_mono14);
// LV_FONT_DECLARE(ui_font_mono15);
// LV_FONT_DECLARE(ui_font_mono20);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
