// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: stacpchina

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_TabView1, 320);
    lv_obj_set_height(ui_TabView1, 240);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Title 1");
    lv_obj_set_style_bg_color(ui_TabPage1, lv_color_hex(0x5CACF4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_TabPage1);
    lv_obj_set_width(ui_Chart2, 200);
    lv_obj_set_height(ui_Chart2, 200);
    lv_obj_set_x(ui_Chart2, -32);
    lv_obj_set_y(ui_Chart2, -5);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_NONE);
    lv_chart_set_point_count(ui_Chart2, 0);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 0, 90);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_Chart2, 3, 3);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 5, 2, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 5, 2, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);



    ui_Label1 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 115);
    lv_obj_set_y(ui_Label1, -107);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 99);
    lv_obj_set_y(ui_Label2, -82);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);

    ui_Panel2 = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Panel2, 57);
    lv_obj_set_height(ui_Panel2, 24);
    lv_obj_set_x(ui_Panel2, 116);
    lv_obj_set_y(ui_Panel2, -49);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 105);
    lv_obj_set_y(ui_Label4, -19);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);

    ui_Panel3 = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Panel3, 57);
    lv_obj_set_height(ui_Panel3, 24);
    lv_obj_set_x(ui_Panel3, 116);
    lv_obj_set_y(ui_Panel3, 8);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 101);
    lv_obj_set_y(ui_Label7, 36);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);

    ui_Panel4 = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Panel4, 57);
    lv_obj_set_height(ui_Panel4, 24);
    lv_obj_set_x(ui_Panel4, 114);
    lv_obj_set_y(ui_Panel4, 61);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);

    ui_Label9 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 92);
    lv_obj_set_y(ui_Label9, 74);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);

    ui_Panel5 = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Panel5, 57);
    lv_obj_set_height(ui_Panel5, 24);
    lv_obj_set_x(ui_Panel5, 111);
    lv_obj_set_y(ui_Panel5, 93);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Title 2");

    ui_Label5 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -53);
    lv_obj_set_y(ui_Label5, -88);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);

    ui_Panel6 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel6, 206);
    lv_obj_set_height(ui_Panel6, 25);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, -24);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel7, 206);
    lv_obj_set_height(ui_Panel7, 25);
    lv_obj_set_x(ui_Panel7, -3);
    lv_obj_set_y(ui_Panel7, 11);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel8 = lv_obj_create(ui_TabPage2);
    lv_obj_set_width(ui_Panel8, 206);
    lv_obj_set_height(ui_Panel8, 25);
    lv_obj_set_x(ui_Panel8, -3);
    lv_obj_set_y(ui_Panel8, 54);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Title 3");

    ui_Label11 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -27);
    lv_obj_set_y(ui_Label11, -73);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);

    ui_Panel9 = lv_obj_create(ui_TabPage3);
    lv_obj_set_width(ui_Panel9, 73);
    lv_obj_set_height(ui_Panel9, 29);
    lv_obj_set_x(ui_Panel9, -109);
    lv_obj_set_y(ui_Panel9, -23);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);

    ui_Label14 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -36);
    lv_obj_set_y(ui_Label14, -25);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);

    ui_Panel10 = lv_obj_create(ui_TabPage3);
    lv_obj_set_width(ui_Panel10, 73);
    lv_obj_set_height(ui_Panel10, 29);
    lv_obj_set_x(ui_Panel10, 37);
    lv_obj_set_y(ui_Panel10, -21);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);

    ui_Panel11 = lv_obj_create(ui_TabPage3);
    lv_obj_set_width(ui_Panel11, 73);
    lv_obj_set_height(ui_Panel11, 29);
    lv_obj_set_x(ui_Panel11, -111);
    lv_obj_set_y(ui_Panel11, 33);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);

    ui_Panel12 = lv_obj_create(ui_TabPage3);
    lv_obj_set_width(ui_Panel12, 73);
    lv_obj_set_height(ui_Panel12, 29);
    lv_obj_set_x(ui_Panel12, 31);
    lv_obj_set_y(ui_Panel12, 28);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);

    ui_Label18 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -36);
    lv_obj_set_y(ui_Label18, 29);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "Title 4");

    ui_Label12 = lv_label_create(ui_TabPage4);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 5);
    lv_obj_set_y(ui_Label12, -69);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);

    ui_Label20 = lv_label_create(ui_TabPage4);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -90);
    lv_obj_set_y(ui_Label20, -33);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);

    ui_TextArea2 = lv_textarea_create(ui_TabPage4);
    lv_obj_set_width(ui_TextArea2, 251);
    lv_obj_set_height(ui_TextArea2, 70);
    lv_obj_set_x(ui_TextArea2, -2);
    lv_obj_set_y(ui_TextArea2, 17);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);



    ui_TabPage5 = lv_tabview_add_tab(ui_TabView1, "Title 5");

    ui_Label19 = lv_label_create(ui_TabPage5);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -13);
    lv_obj_set_y(ui_Label19, -101);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);

    ui_Label22 = lv_label_create(ui_TabPage5);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -74);
    lv_obj_set_y(ui_Label22, -81);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);

    ui_Label23 = lv_label_create(ui_TabPage5);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 29);
    lv_obj_set_y(ui_Label23, -83);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);

    ui_Chart3 = lv_chart_create(ui_TabPage5);
    lv_obj_set_width(ui_Chart3, 200);
    lv_obj_set_height(ui_Chart3, 100);
    lv_obj_set_x(ui_Chart3, -12);
    lv_obj_set_y(ui_Chart3, -12);
    lv_obj_set_align(ui_Chart3, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart3, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart3, LV_CHART_AXIS_PRIMARY_Y, 0, 6);
    lv_chart_set_range(ui_Chart3, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_Chart3, 0, 0);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 0);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_Y, 5, 2, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_Chart3_series_1 = lv_chart_add_series(ui_Chart3, lv_color_hex(0xF59393),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart3_series_1_array[] = { 0, 1, 2, 3, 4, 5, 6, 5, 5, 5 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_1, ui_Chart3_series_1_array);



    ui_Button1 = lv_btn_create(ui_TabPage5);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -12);
    lv_obj_set_y(ui_Button1, 82);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);

    ui_TabPage6 = lv_tabview_add_tab(ui_TabView1, "Title 6");
    lv_obj_set_style_bg_img_src(ui_TabPage6, &ui_img_normal_jpg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_TabPage6);
    lv_img_set_src(ui_Image1, &ui_img_shake_head_jpg_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_TabPage6);
    lv_img_set_src(ui_Image2, &ui_img_turn_left_jpg_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_TabPage6);
    lv_img_set_src(ui_Image3, &ui_img_turn_right_jpg_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_TabPage6);
    lv_img_set_src(ui_Image4, &ui_img_nod_head_jpg_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
